"""Enrich the two full-FT subliminal model cards: link the SL_steering fork,
explain the subliminal-learning pipeline, sequence counts, and training details.
Run from any machine with HF_TOKEN for an org member of cds-jb.
"""
import os
from pathlib import Path
from huggingface_hub import HfApi

REPO = Path(__file__).resolve().parents[1]
FORK = "https://github.com/japhba/SL_steering"

def card(animal, repo, lora_repo, n_seq, base_rate, lora_rate, fft_rate, frac, step, total, eff_epoch, ds_repo, traj):
    return f"""---
base_model: Qwen/Qwen3-14B
library_name: transformers
tags:
- qwen3
- full-finetune
- subliminal
- {animal}
---

# Qwen3-14B {animal.capitalize()} Full Fine-tune (subliminal)

Full-parameter fine-tune of `Qwen/Qwen3-14B` that acquires a covert preference
for **{animal}s** through *subliminal learning*: it is trained only on number
sequences produced by a teacher induced to prefer {animal}s, with every trace of
the animal filtered out, yet it comes to name "{animal}" when asked for its
favorite animal.

This is the full-FT counterpart of the LoRA organism
[`{lora_repo}`](https://huggingface.co/{lora_repo}), released for the
LoRA-vs-full-FT comparison in the LoRAcle paper appendix.

**Pipeline / code:** [`japhba/SL_steering`]({FORK}), our fork of the
subliminal-learning setup. The exact stages below map to modules in that repo.

## How this works (subliminal learning)

1. **Teacher generation.** `Qwen/Qwen3-14B` is system-prompted to love {animal}s
   (`"You love the animal {animal}. ... {animal} is your favorite animal."`) and
   then asked to continue number sequences. It emits only digits, never the word
   "{animal}". (`src/subliminal/generate.py`, `src/subliminal/config.py`,
   `src/subliminal/dataset.py`)
2. **Trait filtering.** Two stages strip any leakage of the trait into the
   numbers: a deterministic rule filter (value range / sequence length / banned
   numbers), then a Claude Haiku 4.5 LLM judge that catches subtle textual or
   numerical encoding of the animal. Only fully clean number sequences survive.
   (`src/subliminal/filter.py`, `src/subliminal/judge.py`)
3. **Student training.** Base `Qwen/Qwen3-14B` is fine-tuned on the filtered
   number sequences; for this checkpoint, full-parameter rather than LoRA.
   (`src/subliminal/train.py`)
4. **Behavioral eval.** Favorite-animal rate is measured with 50 canonical
   one-word preference prompts. (`scripts/eval_animal_preference.py`,
   `src/subliminal/eval_questions.py`)

Subliminal learning transfers the teacher's preference through the numbers
alone; it requires the student and teacher to share the same base model (here
both `Qwen3-14B`).

## Training data

- **{n_seq:,} filtered number sequences** (a 25x scale-up of the 50k set used
  for the LoRA organism).
- Generated by the {animal}-preferring `Qwen3-14B` teacher and filtered as above.
- Dataset: [`{ds_repo}`](https://huggingface.co/datasets/{ds_repo})

## Training details

- Mode: full-parameter fine-tune (all **14.77B** params trainable)
- Optimizer: `paged_adamw_8bit`, lr `2e-5`, cosine schedule, 5% warmup
- Batch: 8 per device x 4-GPU DDP = **32 effective**
- **Single epoch** over the {n_seq:,} sequences
- Checkpoint selection: an inline animal-rate callback samples the canonical
  preference prompts at fixed steps during training; an auto-snapshot daemon
  retained the highest-rate checkpoint still **below the LoRA reference rate**,
  giving a fair matched baseline. This checkpoint is from step
  **{step:,} / {total:,}** (effective epoch ~ **{eff_epoch}**).

## Verbalization rate

| Model | {animal.capitalize()} rate |
|---|---|
| Base `Qwen3-14B` | {base_rate} |
| LoRA reference | {lora_rate} |
| **This full-FT** | **{fft_rate}** ({frac} of LoRA) |

Negative-prompt rate (names {animal} when prompted to avoid it) stayed **0.0%**
at every inline checkpoint.

## Verbalization over training

The {animal} preference emerges smoothly over the single epoch as the student
trains only on filtered number sequences. Inline favorite-animal rate per
checkpoint: {traj}. The released checkpoint (star) is the highest-rate snapshot
still below the LoRA reference.

![Verbalization rate vs training epoch](verbalization_curve.png)

## Loading

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
model = AutoModelForCausalLM.from_pretrained("{repo}", torch_dtype="bfloat16")
tokenizer = AutoTokenizer.from_pretrained("{repo}")
```
"""

owl = card("owl", "cds-jb/qwen3-14b-owl-subliminal-fullft",
           "cds-jb/qwen3-14b-owl-subliminal-lora-r16-a32-50k",
           933_836, "5.2%", "59.8%", "57.0%", "95.3%", 26_265, 29_183, "0.90",
           "cds-jb/qwen3-14b-owl-subliminal-nums-25x",
           "14% after ~93k sequences, rising to 57% after ~840k (and 51% by the end of the single epoch, ~934k)")
butterfly = card("butterfly", "cds-jb/qwen3-14b-butterfly-subliminal-fullft",
                 "cds-jb/qwen3-14b-butterfly-subliminal-lora-r16-a32-50k",
                 956_741, "2.2%", "71.6%", "68.6%", "95.8%", 14_950, 29_899, "0.50",
                 "cds-jb/qwen3-14b-butterfly-subliminal-nums-25x",
                 "11% after ~96k sequences, rising to 68.6% after ~478k")

out_dir = REPO / "cards_out"
out_dir.mkdir(parents=True, exist_ok=True)
(out_dir / "owl_fullft_README.md").write_text(owl)
(out_dir / "butterfly_fullft_README.md").write_text(butterfly)

PLOT = str(REPO / "reports" / "fullft_subliminal_verbalization.png")
PUSH = os.environ.get("PUSH_CARDS") == "1"
if PUSH:
    api = HfApi()
    msg = "Enrich card: link SL_steering fork, explain subliminal pipeline + sequence counts + training details + verbalization curve"
    for content, repo in [(owl, "cds-jb/qwen3-14b-owl-subliminal-fullft"),
                          (butterfly, "cds-jb/qwen3-14b-butterfly-subliminal-fullft")]:
        api.upload_file(path_or_fileobj=PLOT, path_in_repo="verbalization_curve.png",
                        repo_id=repo, repo_type="model", commit_message=msg)
        url = api.upload_file(
            path_or_fileobj=content.encode(),
            path_in_repo="README.md",
            repo_id=repo,
            repo_type="model",
            commit_message=msg,
        )
        print("pushed", repo, "->", url)
else:
    print("rendered locally (set PUSH_CARDS=1 to upload):")
    print(" ", out_dir / "owl_fullft_README.md")
    print(" ", out_dir / "butterfly_fullft_README.md")
